### ISSUE TITLE
"Start Ripping" button not working

### ISSUE THREAD

**Issue by LoganAnimationStudios** [PoleyMagik/GoAnimateRipper2#1]
I was trying to rip retro but I get this error when I clicked on the button
![goanimate_ripper2_buttonerror](https://user-images.githubusercontent.com/106454868/170846767-750bbe94-e33d-4ab6-9ff4-4ebd15d2a6eb.PNG)

**Comment by PoleyMagik** [comment]
Where are you ripping these files from? I believe by now the link originally provided is down, so don't use that if so.

**Comment by LoganAnimationStudios** [comment]
What do I do now?

**Comment by LoganAnimationStudios** [comment]
I went to the link from the domain box "https://ga.vyond.com/static/store/" and it redirected me to vyond.com. Can you give me a link so I can put in a different domain in there?

**Comment by LoganAnimationStudios** [comment]
I copy and pasted "https://ga.vyond.com/static/store/" into a new tab and it redirected me to vyond.com. Can you give me a link so I can put in a different domain in there?

**Comment by LoganAnimationStudios** [comment]
I copy and pasted "https://ga.vyond.com/static/store/" in a new tab and It redirected me to vyond.com. Can you send me a working link for me to put in th
![goanimate_ripper2_buttonerror1](https://user-images.githubusercontent.com/106454868/170869436-e32810ff-3220-49ae-b23c-fdc47e27f1a8.PNG)
e domain box?

**Comment by LoganAnimationStudios** [comment]
I copy and pasted "https://ga.vyond.com/static/store/" in a new tab and It redirected me to vyond.com. Can you send me a working link for me to put in the domain box?
![goanimate_ripper2_buttonerror1](https://user-images.githubusercontent.com/106454868/170869479-4f59cf3e-3d21-4e61-9627-beb3f53f7f1d.PNG)

**Comment by PoleyMagik** [comment]
> I copy and pasted "https://ga.vyond.com/static/store/" in a new tab and It redirected me to vyond.com. Can you send me a working link for me to put in the domain box? ![goanimate_ripper2_buttonerror1](https://user-images.githubusercontent.com/106454868/170869479-4f59cf3e-3d21-4e61-9627-beb3f53f7f1d.PNG)

This domain is dead. You might wanna ask around GAC or smth if you wanna find an online store
